偉人と背景を追加
HakuryuSato/APPRENTICE-TEAMDEV-1-TEAM4 pull request #26
Opened 2024-09-01 05:05 UTC by hiderits8

2024-09-01 08:20 UTC, HakuryuSato reviewed
本の高さは今のところ想定していませんでした。

もし実装するとなると以下の作業が追加で必要となるため、
個人的には時間が余ったら実装という形の方が嬉しいです(;_;)
・DBの構造変更、テスト
・Bookクラスの修正、テスト
・Booksコントローラーの変更、テスト
・Booksモデルの変更、テスト
・fetch関数の変更、テスト

9/2に議論できればと思います！

2024-09-02 12:07 UTC, HakuryuSato requested changes
bookのファイル名は先日Discordで報告させて頂いた通り、
https://discord.com/channels/1158598771597398108/1260033959908216873/1277938482479763508

"柄名_色_厚み(1~4).png"　 に修正頂けないでしょうか、
これはワイヤーフレームの設計を元にコードを作成したためです。

柄に関してもワイヤーフレームでは存在したため含めていましたが、
ないのであれば柄名はなしで、色と厚みだけでも問題ないと思います。

または、現在のファイル名で進めるのであれば、
どの項目が何を示すのかご教示頂きたいです。

以下がファイルの呼び出し用コードです
 *booksディレクトリの追加はこのブランチマージ後に修正します。
bookImage.src = `./images/${this.coverImage}_${this.coverColor}_${this.bookThickness}.png`;

2024-09-02 13:19 UTC, hiderits8 commented
[sml]_[color]_[1-4].png

2024-09-02 13:19 UTC, hiderits8 commented
"[sml]_[color]_[1-4].png"

2024-09-02 14:25 UTC, closed without merging